# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
GET {{host}}/matrix
Accept: application/json

###
GET {{host}}/matrix/1
Accept: application/json

###
POST {{host}}/matrix
Content-Type: application/json
Accept: application/json

{
}

###
POST {{host}}/matrix/fill/1
Content-Type: application/json
Accept: application/json

{
}

###
POST {{host}}/matrix/1/0/9
Content-Type: application/json
Accept: application/json

{
}

###
POST {{host}}/matrix/task
Content-Type: application/json
Accept: application/json

{
  "action": "paint",
  "row": 0,
  "col": 0,
  "value": 5
}


###
POST {{host}}/matrix/task
Content-Type: application/json
Accept: application/json

{
  "action": "invert",
  "row": 1,
  "col": 0
}

###
POST {{host}}/matrix/task
Content-Type: application/json
Accept: application/json

{
  "unreliable": true,
  "action": "invert_fill"
}

###
POST {{host}}/matrix/delayedtask/6
Content-Type: application/json
Accept: application/json

{
  "action": "paint",
  "row": 0,
  "col": 0,
  "value": 5
}

###
POST {{host}}/matrix/concurrent
Content-Type: application/json
Accept: application/json

{
  "fill": 5,
  "paint": [
    [
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0
    ]
  ]
}

###
